### PR TITLE
Message Bus Examples

### PR DESCRIPTION
**Pull request by selvakumaar5496**

### CODE REVIEW

**Comment by hessio** [comment]
Hi @selvakumaar5496 is this PR still relevant? can we close it if it's no longer relevant?

**Comment by hessio** [comment]
Hi @selvakumaar5496 is this PR still relevant? can we close it if it's no longer relevant?

**Comment by hessio** [comment]
@ujjwalpl can you review this PR and if it is no longer relevant can we close it?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
